stages:
  - build
  - deploy

build-code-job:
  tags:
    - ci
  stage: build
  script:
    - pip3 install -r requirements.txt

deploy-code-job:
  tags:
    - ci
  stage: deploy
  script:
    - echo "If the files are built successfully, test some files with one commands:"
