stages:
  - deploy

deploy-code-job:
  tags:
    - ci
  stage: deploy
  script:
    - sudo rsync -avh -e "ssh -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa" --exclude .git /home/gitlab-runner/builds/8UYUucER/0/marutibhosale/new_chatapp  deploy@172.16.1.140:/home/deploy
    - ssh deploy@172.16.1.140 sudo pip3 install -r /home/deploy/new_chatapp/requirements.txt
    - sudo systemctl start gunicorn.service
    - sudo service nginx restart

