stages:
  - build
  - deploy

build-code-job:
  tags:
    - ci
  stage: build
  script:
    - cd /home/ubuntu
    - pwd

deploy-code-job:
  tags:
    - ci
  stage: deploy
  script:
    - echo "If the files are built successfully, test some files with one commands:"
