stages:
  - build
  - deploy

build-code-job:
  tags:
    - ci
  stage: build
  script:
    - cd /
    - sudo git clone https://github.com/marutibhosale/new_chatapp.git

deploy-code-job:
  tags:
    - ci
  stage: deploy
  script:
    - echo "If the files are built successfully, test some files with one command:"
