stages:
  - build
  - deploy

build-code-job:
  tags:
    - ci
  stage: build
  before_script:
    - mkdir new_chatapp
  script:
    - cp . new_chatapp

deploy-code-job:
  tags:
    - ci
  stage: deploy
  script:
    - echo "If the files are built successfully, test some files with one command:"
    - rake test1
